In [1]:
#aggregated transaction
import pandas as pd
import json
import os

path=r'G:/phonepe/data/data/aggregated/transaction/country/india/state/'
Agg_state_list=os.listdir(path)
Agg_state_list
print(Agg_state_list)

clm={'State':[], 'Year':[],'Quarter':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for z in D['data']['transactionData']:
                    clm['Transaction_type'].append(z['name'])
                    clm['Transaction_count'].append(z['paymentInstruments'][0]['count'])
                    clm['Transaction_amount'].append(z['paymentInstruments'][0]['amount'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

aggregated_transaction = pd.DataFrame(clm)

# Show result
print(aggregated_transaction.head())
print("Rows:", len(aggregated_transaction))

['andaman-&-nicobar-islands', 'andhra-pradesh', 'arunachal-pradesh', 'assam', 'bihar', 'chandigarh', 'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu', 'delhi', 'goa', 'gujarat', 'haryana', 'himachal-pradesh', 'jammu-&-kashmir', 'jharkhand', 'karnataka', 'kerala', 'ladakh', 'lakshadweep', 'madhya-pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim', 'tamil-nadu', 'telangana', 'tripura', 'uttar-pradesh', 'uttarakhand', 'west-bengal']
                       State  Year  Quarter          Transaction_type  \
0  andaman-&-nicobar-islands  2018        1  Recharge & bill payments
1  andaman-&-nicobar-islands  2018        1     Peer-to-peer payments
2  andaman-&-nicobar-islands  2018        1         Merchant payments
3  andaman-&-nicobar-islands  2018        1        Financial Services
4  andaman-&-nicobar-islands  2018        1                    Others

   Transaction_count  Transaction_amount
0               4200        1.845307e+06
1               1871        1.213866e+07
2                298        4.525072e+05
3                 33        1.060142e+04
4                256        1.846899e+05
Rows: 5034

In [2]:
aggregated_transaction

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [3]:
#aggregated user

import pandas as pd
import json
import os

# Correct folder path
path = r"/phonepe/data/data/aggregated/user/country/india/state/"

# Get list of states
state_list = os.listdir(path)
print(state_list)

# Create empty dictionary
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Brand': [],
    'Count': [],
    'Percentage': []
}

# Loop through states
for state in state_list:
    state_path = os.path.join(path, state)
    
    if os.path.isdir(state_path):
        years = os.listdir(state_path)
        
        # Loop through years
        for year in years:
            year_path = os.path.join(state_path, year)
            
            if os.path.isdir(year_path):
                quarters = os.listdir(year_path)
                
                # Loop through quarter files
                for quarter_file in quarters:
                    if quarter_file.endswith('.json'):
                        file_path = os.path.join(year_path, quarter_file)
                        
                        with open(file_path, 'r') as f:
                            data = json.load(f)
                            
                            try:
                                users = data["data"]["usersByDevice"]
                                
                                for user in users:
                                    clm['State'].append(state)
                                    clm['Year'].append(int(year))
                                    clm['Quarter'].append(int(quarter_file.strip('.json')))
                                    clm['Brand'].append(user['brand'])
                                    clm['Count'].append(user['count'])
                                    clm['Percentage'].append(user['percentage'])
                            
                            except (KeyError, TypeError):
                                # Some files may not contain usersByDevice
                                pass

# Create DataFrame
aggregated_user = pd.DataFrame(clm)

# Show result
print(aggregated_user.head())
print("Rows:", len(aggregated_user))

['andaman-&-nicobar-islands', 'andhra-pradesh', 'arunachal-pradesh', 'assam', 'bihar', 'chandigarh', 'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu', 'delhi', 'goa', 'gujarat', 'haryana', 'himachal-pradesh', 'jammu-&-kashmir', 'jharkhand', 'karnataka', 'kerala', 'ladakh', 'lakshadweep', 'madhya-pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim', 'tamil-nadu', 'telangana', 'tripura', 'uttar-pradesh', 'uttarakhand', 'west-bengal']
                       State  Year  Quarter    Brand  Count  Percentage
0  andaman-&-nicobar-islands  2018        1   Xiaomi   1665    0.247033
1  andaman-&-nicobar-islands  2018        1  Samsung   1445    0.214392
2  andaman-&-nicobar-islands  2018        1     Vivo    982    0.145697
3  andaman-&-nicobar-islands  2018        1     Oppo    501    0.074332
4  andaman-&-nicobar-islands  2018        1  OnePlus    332    0.049258
Rows: 6732

In [4]:
aggregated_user.info

<bound method DataFrame.info of                           State  Year  Quarter    Brand    Count  Percentage
0     andaman-&-nicobar-islands  2018        1   Xiaomi     1665    0.247033
1     andaman-&-nicobar-islands  2018        1  Samsung     1445    0.214392
2     andaman-&-nicobar-islands  2018        1     Vivo      982    0.145697
3     andaman-&-nicobar-islands  2018        1     Oppo      501    0.074332
4     andaman-&-nicobar-islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                west-bengal  2022        1   Lenovo   330017    0.015056
6728                west-bengal  2022        1  Infinix   284678    0.012987
6729                west-bengal  2022        1     Asus   280347    0.012790
6730                west-bengal  2022        1    Apple   277752    0.012671
6731                west-bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]>

In [5]:
aggregated_user

                          State  Year  Quarter    Brand    Count  Percentage
0     andaman-&-nicobar-islands  2018        1   Xiaomi     1665    0.247033
1     andaman-&-nicobar-islands  2018        1  Samsung     1445    0.214392
2     andaman-&-nicobar-islands  2018        1     Vivo      982    0.145697
3     andaman-&-nicobar-islands  2018        1     Oppo      501    0.074332
4     andaman-&-nicobar-islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                west-bengal  2022        1   Lenovo   330017    0.015056
6728                west-bengal  2022        1  Infinix   284678    0.012987
6729                west-bengal  2022        1     Asus   280347    0.012790
6730                west-bengal  2022        1    Apple   277752    0.012671
6731                west-bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [6]:
#aggregated insurance

path=r'G:/phonepe/data/data/aggregated/insurance/country/india/state/'
state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'Insurance_type':[], 'Count':[], 'Amount':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                try:
                    for z in D['data']['transactionData']:
                        clm['Insurance_type'].append(z['name'])
                        clm['Count'].append(z['paymentInstruments'][0]['count'])
                        clm['Amount'].append(z['paymentInstruments'][0]['amount'])
                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quarter'].append(int(k.strip('.json')))
                except:
                    pass

aggregated_insurance = pd.DataFrame(clm)

# Show result
print(aggregated_insurance.head())
print("Rows:", len(aggregated_insurance))

                       State  Year  Quarter Insurance_type  Count    Amount
0  andaman-&-nicobar-islands  2020        2      Insurance      6    1360.0
1  andaman-&-nicobar-islands  2020        3      Insurance     41   15380.0
2  andaman-&-nicobar-islands  2020        4      Insurance    124  157975.0
3  andaman-&-nicobar-islands  2021        1      Insurance    225  244266.0
4  andaman-&-nicobar-islands  2021        2      Insurance    137  181504.0
Rows: 682

In [7]:
aggregated_insurance

,State,Year,Quarter,Insurance_type,Count,Amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [8]:
#map transaction

path=r'G:/phonepe/data/data/map/transaction/hover/country/india/state/'

state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'District':[], 'Count':[], 'Amount':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for z in D['data']['hoverDataList']:
                    clm['District'].append(z['name'])
                    clm['Count'].append(z['metric'][0]['count'])
                    clm['Amount'].append(z['metric'][0]['amount'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

map_transaction = pd.DataFrame(clm)

print(map_transaction.head())
print("Rows:", len(map_transaction))


import pandas as pd
import json
import os

path = r'G:/phonepe/data/data/map/transaction/hover/country/india/state/'
state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Count': [],
    'Amount': []
}

for state in state_list:
    state_path = os.path.join(path, state)
    
    if os.path.isdir(state_path):
        years = os.listdir(state_path)
        
        for year in years:
            year_path = os.path.join(state_path, year)
            
            if os.path.isdir(year_path):
                quarters = os.listdir(year_path)
                
                for quarter_file in quarters:
                    if quarter_file.endswith('.json'):
                        file_path = os.path.join(year_path, quarter_file)
                        
                        with open(file_path, 'r') as f:
                            data = json.load(f)
                            
                            try:
                                districts = data['data']['hoverDataList']
                                
                                for d in districts:
                                    clm['State'].append(state)
                                    clm['Year'].append(int(year))
                                    clm['Quarter'].append(int(quarter_file.strip('.json')))
                                    clm['District'].append(d['name'])
                                    clm['Count'].append(d['metric'][0]['count'])
                                    clm['Amount'].append(d['metric'][0]['amount'])
                            
                            except (KeyError, TypeError):
                                pass

map_transaction = pd.DataFrame(clm)

print(map_transaction.head())
print("Rows:", len(map_transaction))

                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2018        1
1  andaman-&-nicobar-islands  2018        1
2  andaman-&-nicobar-islands  2018        1
3  andaman-&-nicobar-islands  2018        2
4  andaman-&-nicobar-islands  2018        2

                            District  Count        Amount
0  north and middle andaman district    442  9.316631e+05
1             south andaman district   5688  1.256025e+07
2                  nicobars district    528  1.139849e+06
3  north and middle andaman district    825  1.317863e+06
4             south andaman district   9395  2.394824e+07
Rows: 20604
                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2018        1
1  andaman-&-nicobar-islands  2018        1
2  andaman-&-nicobar-islands  2018        1
3  andaman-&-nicobar-islands  2018        2
4  andaman-&-nicobar-islands  2018        2

                            District  Count        Amount
0  north and middle andaman district    442  9.316631e+05
1             south andaman district   5688  1.256025e+07
2                  nicobars district    528  1.139849e+06
3  north and middle andaman district    825  1.317863e+06
4             south andaman district   9395  2.394824e+07
Rows: 20604

In [9]:
map_transaction

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [10]:
#  map user

path='G:/phonepe/data/data/map/user/hover/country/india/state/'

state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'District':[], 'Registered_users':[], 'App_opens':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for district,data in D['data']['hoverData'].items():
                    clm['District'].append(district)
                    clm['Registered_users'].append(data['registeredUsers'])
                    clm['App_opens'].append(data['appOpens'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

map_user = pd.DataFrame(clm)

print(map_user.head())
print("Rows:", len(map_user))

                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2018        1
1  andaman-&-nicobar-islands  2018        1
2  andaman-&-nicobar-islands  2018        1
3  andaman-&-nicobar-islands  2018        2
4  andaman-&-nicobar-islands  2018        2

                            District  Registered_users  App_opens
0  north and middle andaman district               632          0
1             south andaman district              5846          0
2                  nicobars district               262          0
3  north and middle andaman district               911          0
4             south andaman district              8143          0
Rows: 20608

In [11]:
map_user

,State,Year,Quarter,District,Registered_users,App_opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [12]:
#  map insurance

path=r'G:/phonepe/data/data/map/insurance/hover/country/india/state/'

state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'District':[], 'Count':[], 'Amount':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for z in D['data']['hoverDataList']:
                    clm['District'].append(z['name'])
                    clm['Count'].append(z['metric'][0]['count'])
                    clm['Amount'].append(z['metric'][0]['amount'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

map_insurance = pd.DataFrame(clm)

print(map_insurance.head())
print("Rows:", len(map_insurance))

                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2020        2
1  andaman-&-nicobar-islands  2020        2
2  andaman-&-nicobar-islands  2020        3
3  andaman-&-nicobar-islands  2020        3
4  andaman-&-nicobar-islands  2020        3

                            District  Count   Amount
0             south andaman district      3    795.0
1                  nicobars district      3    565.0
2  north and middle andaman district      1    281.0
3             south andaman district     35  13651.0
4                  nicobars district      5   1448.0
Rows: 13876

In [13]:
map_insurance

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

In [14]:
#  top transaction

path='G:/phonepe/data/data/top/transaction/country/india/state/'
state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'Pincode':[], 'Count':[], 'Amount':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for z in D['data']['pincodes']:
                    clm['Pincode'].append(z['entityName'])
                    clm['Count'].append(z['metric']['count'])
                    clm['Amount'].append(z['metric']['amount'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

top_transaction = pd.DataFrame(clm)

print(top_transaction.head())
print("Rows:", len(top_transaction))

                       State  Year  Quarter Pincode  Count        Amount
0  andaman-&-nicobar-islands  2018        1  744101   1622  2.769298e+06
1  andaman-&-nicobar-islands  2018        1  744103   1223  2.238042e+06
2  andaman-&-nicobar-islands  2018        1  744102    969  3.519060e+06
3  andaman-&-nicobar-islands  2018        1  744105    685  1.298561e+06
4  andaman-&-nicobar-islands  2018        1  744104    340  1.039715e+06
Rows: 9999

In [15]:
top_transaction

                          State  Year  Quarter Pincode    Count        Amount
0     andaman-&-nicobar-islands  2018        1  744101     1622  2.769298e+06
1     andaman-&-nicobar-islands  2018        1  744103     1223  2.238042e+06
2     andaman-&-nicobar-islands  2018        1  744102      969  3.519060e+06
3     andaman-&-nicobar-islands  2018        1  744105      685  1.298561e+06
4     andaman-&-nicobar-islands  2018        1  744104      340  1.039715e+06
...                         ...   ...      ...     ...      ...           ...
9994                west-bengal  2024        4  711101  6753348  1.049483e+10
9995                west-bengal  2024        4  700059  6662715  8.009476e+09
9996                west-bengal  2024        4  700039  6575693  9.018748e+09
9997                west-bengal  2024        4  734001  6432082  8.996529e+09
9998                west-bengal  2024        4  733134  6313560  1.050259e+10

[9999 rows x 6 columns]

In [16]:
# top user

path='G:/phonepe/data/data/top/user/country/india/state/'
state_list=os.listdir(path)

clm={'State':[], 'Year':[],'Quarter':[],'District':[], 'Registered_users':[]}

for i in state_list:
    p_i=path+i+"/"
    yr=os.listdir(p_i)
    for j in yr:
        p_j=p_i+j+"/"
        qtr=os.listdir(p_j)
        for k in qtr:
            p_k=p_j+k
            with open(p_k,'r') as Data:
                D=json.load(Data)
                for z in D['data']['districts']:
                    clm['District'].append(z['name'])
                    clm['Registered_users'].append(z['registeredUsers'])
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

top_user = pd.DataFrame(clm)

print(top_user.head())
print("Rows:", len(top_user))

                       State  Year  Quarter                  District  \
0  andaman-&-nicobar-islands  2018        1             south andaman
1  andaman-&-nicobar-islands  2018        1  north and middle andaman
2  andaman-&-nicobar-islands  2018        1                  nicobars
3  andaman-&-nicobar-islands  2018        2             south andaman
4  andaman-&-nicobar-islands  2018        2  north and middle andaman

   Registered_users
0              5846
1               632
2               262
3              8143
4               911
Rows: 8296

In [17]:
top_user

,State,Year,Quarter,District,Registered_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,west-bengal,2024,4,hooghly,1957356
8292,west-bengal,2024,4,nadia,1861738
8293,west-bengal,2024,4,purba medinipur,1717074
8294,west-bengal,2024,4,paschim medinipur,1522845
8295,west-bengal,2024,4,paschim bardhaman,1468252

In [18]:
top_user

,State,Year,Quarter,District,Registered_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,west-bengal,2024,4,hooghly,1957356
8292,west-bengal,2024,4,nadia,1861738
8293,west-bengal,2024,4,purba medinipur,1717074
8294,west-bengal,2024,4,paschim medinipur,1522845
8295,west-bengal,2024,4,paschim bardhaman,1468252

In [19]:
#  top insurance

import pandas as pd
import json
import os

path = r'G:/phonepe/data/data/top/insurance/country/india/state/'
state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Count': [],
    'Amount': []
}

for state in state_list:
    state_path = os.path.join(path, state)
    
    if os.path.isdir(state_path):
        years = os.listdir(state_path)
        
        for year in years:
            year_path = os.path.join(state_path, year)
            
            if os.path.isdir(year_path):
                quarters = os.listdir(year_path)
                
                for quarter_file in quarters:
                    if quarter_file.endswith('.json'):
                        file_path = os.path.join(year_path, quarter_file)
                        
                        with open(file_path, 'r') as f:
                            data = json.load(f)
                            
                            try:
                                districts = data['data']['districts']
                                
                                for d in districts:
                                    clm['State'].append(state)
                                    clm['Year'].append(int(year))
                                    clm['Quarter'].append(int(quarter_file.strip('.json')))
                                    clm['District'].append(d['entityName'])  # ✅ FIXED
                                    clm['Count'].append(d['metric']['count'])
                                    clm['Amount'].append(d['metric']['amount'])
                            
                            except (KeyError, TypeError):
                                pass

top_insurance = pd.DataFrame(clm)

print(top_insurance.head())
print("Rows:", len(top_insurance))

                       State  Year  Quarter                  District  Count  \
0  andaman-&-nicobar-islands  2020        2                  nicobars      3
1  andaman-&-nicobar-islands  2020        2             south andaman      3
2  andaman-&-nicobar-islands  2020        3             south andaman     35
3  andaman-&-nicobar-islands  2020        3                  nicobars      5
4  andaman-&-nicobar-islands  2020        3  north and middle andaman      1

    Amount
0    565.0
1    795.0
2  13651.0
3   1448.0
4    281.0
Rows: 5608

In [20]:
top_insurance

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2020,2,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,3,south andaman,35,13651.0
3,andaman-&-nicobar-islands,2020,3,nicobars,5,1448.0
4,andaman-&-nicobar-islands,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,west-bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,west-bengal,2024,4,paschim medinipur,4155,5405054.0
5605,west-bengal,2024,4,malda,4042,4902098.0
5606,west-bengal,2024,4,nadia,3807,5031294.0
5607,west-bengal,2024,4,purba bardhaman,3595,4482879.0

In [ ]:
from sqlalchemy import create_engine, text

# sql table creation

#   DB details
engine = create_engine(
    "postgresql+psycopg2://dinesh:VUgcYZp5hqNQFpgVlZINRvDpqmLYMvck@dpg-d6u0ifi4d50c73cje580-a.singapore-postgres.render.com:5432/phonepe_aiml_project"
)

queries = [

# 1️.Aggregated Transaction
"""
CREATE TABLE IF NOT EXISTS aggregated_transaction (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    transaction_type VARCHAR(100),
    transaction_count BIGINT,
    transaction_amount FLOAT
);
""",

# 2️.Aggregated User
"""
CREATE TABLE IF NOT EXISTS aggregated_user (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    brand VARCHAR(100),
    registered_users BIGINT,
    app_opens BIGINT
);
""",

# 3️.Aggregated Insurance
"""
CREATE TABLE IF NOT EXISTS aggregated_insurance (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    insurance_type VARCHAR(100),
    policy_count BIGINT,
    premium_amount FLOAT
);
""",

# 4️. Map Transaction
"""
CREATE TABLE IF NOT EXISTS map_transaction (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    transaction_count BIGINT,
    transaction_amount FLOAT
);
""",

# 5️. Map User
"""
CREATE TABLE IF NOT EXISTS map_user (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    registered_users BIGINT
);
""",

# 6️. Map Insurance
"""
CREATE TABLE IF NOT EXISTS map_insurance (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    insurance_type VARCHAR(100),
    policy_count BIGINT,
    premium_amount FLOAT
);
""",

# 7️. Top Transaction
"""
CREATE TABLE IF NOT EXISTS top_transaction (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    transaction_count BIGINT,
    transaction_amount FLOAT
);
""",

# 8️. Top User
"""
CREATE TABLE IF NOT EXISTS top_user (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    registered_users BIGINT
);
""",

# 9️. Top Insurance
"""
CREATE TABLE IF NOT EXISTS top_insurance (
    id SERIAL PRIMARY KEY,
    state VARCHAR(100),
    district VARCHAR(100),
    year INT,
    quarter INT,
    insurance_type VARCHAR(100),
    policy_count BIGINT,
    premium_amount FLOAT
);
"""
]

# Execute
with engine.connect() as conn:
    for q in queries:
        conn.execute(text(q))
    conn.commit()

print("✅ All 9 PhonePe tables created successfully!")

In [21]:
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine("postgresql+psycopg2://dinesh:VUgcYZp5hqNQFpgVlZINRvDpqmLYMvck@dpg-d6u0ifi4d50c73cje580-a.singapore-postgres.render.com:5432/phonepe_aiml_project")


# Upload aggregated tables
aggregated_transaction.to_sql(
    "aggregated_transaction", engine, if_exists="replace", index=False
)

aggregated_user.to_sql(
    "aggregated_user", engine, if_exists="replace", index=False
)

aggregated_insurance.to_sql(
    "aggregated_insurance", engine, if_exists="replace", index=False
)

# Upload map tables
map_transaction.to_sql(
    "map_transaction", engine, if_exists="replace", index=False
)

map_user.to_sql(
    "map_user", engine, if_exists="replace", index=False
)

map_insurance.to_sql(
    "map_insurance", engine, if_exists="replace", index=False
)

# Upload top tables
top_transaction.to_sql(
    "top_transaction", engine, if_exists="replace", index=False
)

top_user.to_sql(
    "top_user", engine, if_exists="replace", index=False
)

top_insurance.to_sql(
    "top_insurance", engine, if_exists="replace", index=False
)

print("✅ All DataFrames uploaded successfully!")

✅ All DataFrames uploaded successfully!